### PR TITLE
Unit tests for AnnotationLoader and DelegatingLoader

### PR DESCRIPTION
**Pull request by rusnak**
Hi!

This PR contains tests around AnnotationLoader and DelegatingLoader classes.

Please review it. If you have any questions or comments, please feel free to ask.

### CODE REVIEW

**Comment by rusnak** [comment]
By the way, I found strange construction in AnnotationLoader class:
```php
if (isset($annotation->mappingExtensionClass)) {
    $fieldsWithHydrationStrategy[$mappedFieldName][ClassMetadata::INDEX_EXTENSION_CLASS] = $annotation->mappingExtensionClass;
}
```

There are no attribute 'mappingExtensionClass' in any annotation.

**Comment by rusnak** [comment]
ClassMetadataLoader fixtures are generalized and extended. From now each metadata fixture are used for AnnotationLoader and InnerPhpLoader(and InnerYamlLoader in the future).

Same thing with the unit tests, one set of tests will be used for AnnotationLoader, InnerPhpLoader and InnerYamlLoader.

And finally I found some differences in functionality AnnotationLoader and InnerPhpLoader:
* InnerPhpLoader do not set RefDefaultSource.
* InnerPhpLoader do not set fieldsWithSourcesForbidden
* InnerPhpLoader do not set getters
* InnerPhpLoader do not set setters
* pre* and post* hooks in the AnnotationLoader use 'method' only and 'class' is totally ignored

I can fix those errors, but not sure of the consequences.

**Comment by rusnak** [comment]
InnerYamlLoader tests added.

**Comment by rusnak** [comment]
Hi!
@kassko, what will be more easy for you?
* create separate PR for each piece of tests
* or append all pieces to one big PR

**Comment by kassko** [comment]
I think make a separation for each directory on 'first level' (like you are doing with ClassMetadaLoader) is nice.

It will be easier to divide the work. I could work on Hydrator tests while you work on ClassMetadataLoader tests or another directory.

I'm going to push a branch with tests on the directory Hydrator.

**Comment by kassko** [comment]
I hope I can check and merge your work this week end. Thanks a lot.

**Comment by rusnak** [comment]
@kassko, any update on this PR?

**Comment by kassko** [comment]
Hello !
@rusnak, I'll be back Tuesday.

**Comment by kassko** [comment]
Hi Alexey,

I know that the loaders are not corrects. In documentation, I will advise to use only the annotation loader until the others are fixed.

I merge.

**Pull request merged**
